version.major=1
version.minor=0
version.patch=0
version.stage=official
version.publish=false

#`version.stage=` If the value is `Beta`, it's considered a test version and will be released as a preview version. Another value is `Alpha`. If the value is `Alpha`, uploading to GitHub won't trigger a workflow build or release, but the word "Alpha" will appear after the application (APK) version number. A third value is `official`, which is the official version. This will trigger a workflow build and release the version, marking the official release.

#`version.publish=` If the value is false, only `test.yml` will be run without producing any build artifacts. Conversely, if the value is true, `build.yml` will be run and the version will be published.