version.major=1
version.minor=0
version.patch=0
version.stage=Alpha
version.beta=1
version.publish=false

#If the value of `#`version.stage=` is `Beta`, it indicates that this is a beta version, which will be released as a preview. Another value is `Alpha`. If the value is `Alpha`, uploading to the GitHub repository will not trigger any workflow builds or version releases. The third value is `official`, which represents the official version. This will trigger workflow builds and release the version, marking a formal release.

#`version.publish=` If the value is false, only `test.yml` will be run without producing any build artifacts. Conversely, if the value is true, `build.yml` will be run and the version will be published.