name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      
      - name: Build Android
        run: ./gradlew assembleRelease -Pandroid.aapt2FromMavenOverride=
      
      - name: Organize Artifacts
        run: |
          mkdir -p dist
          mv androidApp/build/outputs/apk/release/*.apk dist/
        shell: bash

      - name: Sign Android APK
        uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDir: dist
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: "36.0.0"

      - name: Rename Signed APK
        run: |
          mv ${{ steps.sign_app.outputs.signedFile }} Knit-${{ github.ref_name }}-unsigned.apk
        shell: bash
      
      - name: Upload Android artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Knit-${{ github.ref_name }}-unsigned.apk
          path: Knit-${{ github.ref_name }}-unsigned.apk
          archive: false
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v8
        with:
          name: Knit-${{ github.ref_name }}-unsigned.apk
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG="${{ github.ref_name }}"
          ARGS=""
          if [[ "$TAG" == *"-beta"* ]]; then
            ARGS="--prerelease"
          fi
          gh release create "$TAG" Knit-${{ github.ref_name }}-unsigned.apk $ARGS --title "$TAG" --generate-notes
        shell: bash
