name: Deploy Website

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      
      - name: Build Web
        run: ./gradlew :webApp:wasmJsBrowserDistribution -Pandroid.aapt2FromMavenOverride=
      
      - name: Organize Artifacts
        run: |
          mkdir -p staging
          cp -r webApp/build/dist/wasmJs/productionExecutable/* staging/
        shell: bash
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'staging/'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
